# Generated by Django 5.1.4 on 2024-12-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Anime')),
                ('jadwal_tayang', models.CharField(max_length=255, verbose_name='Jadwal Tayang')),
                ('studio', models.CharField(max_length=255, verbose_name='Studio Produksi')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('durasi_per_eps', models.CharField(max_length=50, verbose_name='Durasi per Episode')),
                ('sumber', models.CharField(max_length=255, verbose_name='Sumber (Source)')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('link_anime', models.URLField(max_length=500, verbose_name='Link Anime')),
            ],
        ),
    ]
